apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bingo
  template:
    metadata:
      labels:
        app: bingo
    spec:
      containers:
      - name: bingo
        image: bingo-devsecops
        ports:
        - containerPort: 3000
